Repository openshift-knative/net-istio, pull requests merged in 2025-02, with the labels that each got.

#184 [release-v1.17] Update Konflux configurations
  .konflux/applications/serverless-operator-137/components/imagerepositories/net-istio-controller-117.yaml
  .konflux/applications/serverless-operator-137/components/imagerepositories/net-istio-webhook-117.yaml
  .konflux/applications/serverless-operator-137/components/net-istio-controller-117.yaml
  .konflux/applications/serverless-operator-137/components/net-istio-webhook-117.yaml
  .tekton/docker-build.yaml
  .tekton/net-istio-controller-117-pull-request.yaml
  .tekton/net-istio-controller-117-push.yaml
  .tekton/net-istio-webhook-117-pull-request.yaml
  .tekton/net-istio-webhook-117-push.yaml
Labels: approved, lgtm, ok-to-test

#160 [release-v1.15] Update Konflux configurations
  .konflux/applications/serverless-operator-135/serverless-operator-135.yaml
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
  .tekton/docker-build.yaml
Labels: approved, lgtm, ok-to-test

#181 [release-v1.16] Update Konflux configurations
  .konflux/applications/serverless-operator-136/serverless-operator-136.yaml
  .konflux/applications/serverless-operator-136/tests/ec-test.yaml
  .konflux/applications/serverless-operator-136/tests/override-snapshot-ec-test.yaml
  .tekton/docker-build.yaml
Labels: approved, lgtm, ok-to-test

#192 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test

#193 [release-v1.15] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, ok-to-test

#195 [release-v1.17] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, ok-to-test

#194 [release-v1.16] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
Labels: approved, lgtm, ok-to-test

#206 [release-v1.17] Use hacks directly
  openshift/generate.sh
Labels: approved, lgtm

#231 [release-v1.15] Update Konflux configurations
  renovate.json
Labels: approved, lgtm, ok-to-test

#233 [release-v1.17] Update Konflux configurations
  renovate.json
Labels: approved, lgtm, ok-to-test

#254 [main] Update dependabot configurations
  renovate.json
Labels: approved, lgtm, ok-to-test

#257 Update dependabot config ignore istio major minor version
  .github/dependabot.yml
Labels: approved, lgtm

#265 Update dependabot config for all branches
  .github/dependabot.yml
Labels: approved, lgtm

#268 Allow istio patch versions to be grouped
  .github/dependabot.yml
Labels: approved, lgtm
