Repository openshift-knative/net-istio, pull requests merged in 2025-04, with the labels that each got.

#296 [release-v1.16] Update Konflux configurations
  .konflux/applications/serverless-operator-136/components/net-istio-controller-116.yaml
  .konflux/applications/serverless-operator-136/components/net-istio-webhook-116.yaml
  .tekton/docker-build.yaml
  .tekton/net-istio-controller-116-pull-request.yaml
  .tekton/net-istio-controller-116-push.yaml
  .tekton/net-istio-webhook-116-pull-request.yaml
  .tekton/net-istio-webhook-116-push.yaml
Labels: lgtm, ok-to-test

#319 [release-v1.16] Update Konflux configurations
  .tekton/net-istio-controller-116-pull-request.yaml
  .tekton/net-istio-controller-116-push.yaml
  .tekton/net-istio-webhook-116-pull-request.yaml
  .tekton/net-istio-webhook-116-push.yaml
Labels: lgtm

#330 Update OWNERS
  OWNERS
Labels: approved

#297 [release-v1.17] Update Konflux configurations
  .tekton/docker-build.yaml
  .tekton/net-istio-controller-117-pull-request.yaml
  .tekton/net-istio-controller-117-push.yaml
  .tekton/net-istio-webhook-117-pull-request.yaml
  .tekton/net-istio-webhook-117-push.yaml
Labels: needs-ok-to-test
